// Generated by CodiumAI

import { BadRequestException } from '@nestjs/common';
import { AuthService } from './auth.service';
import { User } from 'src/user/entities/user.entity';

describe('AuthService', () => {
  // Test that when login is called with an incorrect email, it throws a BadRequestException with the message 'Email incorreto'.
  
});
